server.port: 9082
spring:
  datasource:
    url: jdbc:h2:file:./target/axon-sample
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    generate-ddl: true
    #hibernate.ddl-auto: update
logging:
 level:
  # ROOT: TRACE
  # org.springframework.security: TRACE
  org.axonframework.tes: TRACE
axon-demo:
 direct: true
